### ISSUE TITLE
Lintint fails with error with Angular 14.2.1.

### ISSUE THREAD

**Issue by PavelSkopik** [angular-eslint/angular-eslint#1122]
When running `ng lint` with Angular 14.2.1 the process fails with the following error:

```sh
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This occurs after upgrading from Angular version 13 using ng update.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `14.0.3` |
| `ESLint`                           | `8.22.0` |
| `node`                             | `16.13.0` |

```sh
Angular CLI: 14.2.1
Node: 16.13.0
Package Manager: yarn 1.21.1
OS: win32 x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cdk                    13.0.2
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.4.0
typescript                      4.8.2
```

**Comment by JamesHenry** [comment]
Hi @PavelSkopik I just released `14.0.4` which officially support Angular 14.2 and TS 4.8, the combination you are using here. I applied it to a new workspace and did not observe any issues, please give it a try!

**Comment by PavelSkopik** [comment]
Hi @JamesHenry,

Awesome, thanks for such a quick response! Will checkout the new release.

**Comment by a-kyryliuk** [comment]
Hi @JamesHenry, the same error still exists for Angular 14.2.1

**Comment by elcreator** [comment]
Hi @JamesHenry, the same issue still exists for Angular 14.2.1

Angular CLI: 14.2.2
Node: 14.19.1
@angular-devkit/architect       0.1402.2
@angular-devkit/build-angular   14.2.2
@angular-devkit/core            14.2.2
@angular-devkit/schematics      14.2.2
@angular/cdk                    14.2.1
@angular/cli                    14.2.2
@angular/flex-layout            14.0.0-beta.40
@schematics/angular             14.2.2
rxjs                            7.5.6
typescript                      4.7.4

**Comment by JamesHenry** [comment]
@elcreator as noted above, I have not been able to reproduce this issue. Please kindly provide a reproduction and I can look into it for you

**Comment by elcreator** [comment]
to everyone who will google this thread: look for extra commas in tsconfig.json before closing }
i.e.
    "paths": {
      "~/shared/*": ["./src/app/shared/*"],
    }

should be

    "paths": {
      "~/shared/*": ["./src/app/shared/*"]
    }

....

    "lib": [
      "es2018",
      "dom"
    ],
}
should be
    "lib": [
      "es2018",
      "dom"
    ]
}
