### ISSUE TITLE
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser. The file does not match your project config: .eslintrc.js

### ISSUE THREAD

**Issue by denys5dev** [angular-eslint/angular-eslint#123]
I faced with  parser error in  .eslintrc.js file  with VS Code.

Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.eslint

ng lint will work totaly fine but if you using hasky with lint-staged for pre-commits it will trown an error:

 0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided

This configuration of **tsconfig.eslint.json** and **restart VSCode** after helped for me:
```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "noEmit": true
  },
  "include": ["src", "e2e", ".eslintrc.js"]
}
```

Most probably this is not issue of @anlguar/eslint but I didn't found better place for this post, maybe you can add this remark to the instalation procces docs until we do more investigation about this beheviour. Or just leave it here maybe this post will help somebody solve this small issue. 

deps:
```
{
  "name": "eslint-helper",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged --relative"
    }
  },
  "lint-staged": {
    "*.{js,ts}": [
       "eslint --fix"
    ]
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.14",
    "@angular/common": "~10.0.14",
    "@angular/compiler": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/forms": "~10.0.14",
    "@angular/platform-browser": "~10.0.14",
    "@angular/platform-browser-dynamic": "~10.0.14",
    "@angular/router": "~10.0.14",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.8",
    "@angular-eslint/builder": "0.2.0-beta.1",
    "@angular-eslint/eslint-plugin": "0.2.0-beta.1",
    "@angular-eslint/eslint-plugin-template": "0.2.0-beta.1",
    "@angular-eslint/schematics": "^0.2.0-beta.1",
    "@angular-eslint/template-parser": "0.2.0-beta.1",
    "@angular/cli": "~10.0.8",
    "@angular/compiler-cli": "~10.0.14",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "3.9.0",
    "@typescript-eslint/parser": "3.9.0",
    "codelyzer": "^6.0.0",
    "eslint": "^7.6.0",
    "husky": "^4.2.5",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "lint-staged": "^10.2.13",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
```

**Comment by alan-agius4** [comment]
I do get the same error, when using the lint builder and adding a `@typescript-eslint` which requires type checking.

```git
diff --git a/.eslintrc.js b/.eslintrc.js
index d41d78d..8181355 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -24,6 +24,10 @@ module.exports = {
   },
 
   rules: {
+    '@typescript-eslint/no-misused-promises': [
+      'error'
+    ],
+
     // ORIGINAL tslint.json -> "directive-selector": [true, "attribute", "app", "camelCase"],
     '@angular-eslint/directive-selector': [
       'error',
(END)
```

```
ng run eslint-issue:eslint
Linting "eslint-issue"...
An unhandled exception occurred: Error while loading rule '@typescript-eslint/no-misused-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/alanagius/cli-repos/eslint-issue/src/app/app.component.html
See "/private/var/folders/mp/zsgl3srd389_js72bk4_bkgh0000gn/T/ng-tFGOVO/angular-errors.log" for further details.
```

Log file
```
[error] Error: Error while loading rule '@typescript-eslint/no-misused-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/alanagius/cli-repos/eslint-issue/src/app/app.component.html
    at Object.getParserServices (/Users/alanagius/cli-repos/eslint-issue/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/getParserServices.js:16:15)
    at create (/Users/alanagius/cli-repos/eslint-issue/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises.js:60:37)
    at Object.create (/Users/alanagius/cli-repos/eslint-issue/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/RuleCreator.js:13:24)
    at createRuleListeners (/Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:761:21)
    at /Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:931:31
    at Array.forEach (<anonymous>)
    at runRules (/Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:876:34)
    at Linter._verifyWithoutProcessors (/Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:1173:31)
    at Linter._verifyWithConfigArray (/Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:1271:21)
    at Linter.verify (/Users/alanagius/cli-repos/eslint-issue/node_modules/eslint/lib/linter/linter.js:1226:25)
```

From the error it looks like are the root cause of this issue is because HTML templates are trying to be linted using `@typescript-eslint`. I managed to fix this by using the overrides sections.

```
diff --git a/.eslintrc.js b/.eslintrc.js
index d41d78d..1a590e1 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -7,38 +7,40 @@
  * consider converting this once you have read through the comments.
  */
 module.exports = {
-  /**
-   * See packages/eslint-plugin/src/configs/README.md
-   * for what this recommended config contains.
-   */
-  extends: [
-    'plugin:@angular-eslint/recommended',
-  ],
 
-  /**
-   * We use a dedicated tsconfig file for the compilation related to linting so that we
-   * have complete control over what gets included and we can maximize performance
-   */
-  parserOptions: {
-    project: './tsconfig.eslint.json',
-  },
 
   rules: {
-    // ORIGINAL tslint.json -> "directive-selector": [true, "attribute", "app", "camelCase"],
-    '@angular-eslint/directive-selector': [
-      'error',
-      { type: 'attribute', prefix: 'app', style: 'camelCase' },
-    ],
-
-    // ORIGINAL tslint.json -> "component-selector": [true, "element", "app", "kebab-case"],
-    '@angular-eslint/component-selector': [
-      'error',
-      { type: 'element', prefix: 'app', style: 'kebab-case' },
-    ],
-
     quotes: ['error', 'single', { allowTemplateLiterals: true }],
   },
   overrides: [
+    {
+      extends: [
+        'plugin:@angular-eslint/recommended',
+      ],
+      parserOptions: {
+        project: './tsconfig.eslint.json',
+      },
+
+      files: ['*.ts'],
+      parser: '@typescript-eslint/parser',
+      rules: {
+        '@typescript-eslint/no-misused-promises': [
+          'error'
+        ],
+        // ORIGINAL tslint.json -> "directive-selector": [true, "attribute", "app", "camelCase"],
+        '@angular-eslint/directive-selector': [
+          'error',
+          { type: 'attribute', prefix: 'app', style: 'camelCase' },
+        ],
+
+        // ORIGINAL tslint.json -> "component-selector": [true, "element", "app", "kebab-case"],
+        '@angular-eslint/component-selector': [
+          'error',
+          { type: 'element', prefix: 'app', style: 'kebab-case' },
+        ],
+
+      }
+    },
     /**
      * This extra piece of configuration is only necessary if you make use of inline
      * templates within Component metadata, e.g.:
(END)
```

**Comment by JamesHenry** [comment]
Thanks folks, please check out the PR I just merged for a full write up on this topic #125 (as well as the updated README at the root).

I just released the breaking change update as `v0.3.0-beta.1`.

**Comment by JamesHenry** [comment]
As per previous comments, for anyone coming to this thread, please follow the structure which is created in v0.3+ of the toolset and is used in the integration-tests package within this repo

**Comment by hossein13m** [comment]
I have added the following code in my `eslintrc.json` file, and I am using the `"@angular-eslint/eslint-plugin": "^13.0.1"`  but there I still get the following error:

`
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/app/app.component.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config.
`

here is an overview of my eslint config file:

`
"extends": [
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/recommended"
    ],
    "overrides": [
        {
            "files": ["*.ts", "*.component.html", "*.component.ts"],
            "parserOptions": {
                "project": ["./tsconfig.json"],
                "extraFileExtensions": [".html"]
            },
            "rules": { "@typescript-eslint/prefer-nullish-coalescing": "error" }
        }
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
`

Am I doing something wrong?

**Comment by hossein13m** [comment]
I have added the following code in my _eslintrc.json_ file, and I am using the `"@angular-eslint/eslint-plugin": "^13.0.1"` but there I still get the following error:

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/app/app.component.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config.
```

here is an overview of my eslint config file:


```
{
    "extends": [
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/recommended"
    ],
    "overrides":  
        {
            "files": ["*.ts", "*.component.html", "*.component.ts"],
            "parserOptions": {
                "project": ["./tsconfig.json"],
                "extraFileExtensions": [".html"]
            },
            "rules": { "@typescript-eslint/prefer-nullish-coalescing": "error" }
        }
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
}
```

**Am I doing something wrong?**

**Comment by KikoCosmetics** [comment]
@hossein13m hi, is there any news? I'm getting the same error, but it doesn't make sense!
