### ISSUE TITLE
@angular-eslint/schematics: missing "tsconfigRootDir" for nested projects in parserOptions

### ISSUE THREAD

**Issue by ChristophRSG** [angular-eslint/angular-eslint#609]
## Description

When adding ESLint with `angular-eslint` to a "nested" project, (i.e. projects in the "projects" folder), IDEs (tested with **VS Code**  and **IntelliJ** can't recognize the .eslintrc.json.

`yarn lint <project>` still works, but the highlighting in the IDE willl not.

## Solution

Adding `"tsconfigRootDir": "../../",` to "parserOptions" solves the issue:

```json
...
      "parserOptions": {
        "tsconfigRootDir": "../../",
        "project": [
          "projects/testlib/tsconfig.lib.json",
          "projects/testlib/tsconfig.spec.json"
        ],
        "createDefaultProgram": true
      },
...
```

## Steps to reproduce

- `ng add testapp`
- `ng g library testlib`
- `ng add @angular-eslint/schematics`
- `ng g @angular-eslint/schematics:add-eslint-to-project testapp`
- `ng g @angular-eslint/schematics:add-eslint-to-project testlib`

The configuration in `projects/testlib/.eslintrc.json` will be generated like this:

```json
{
  "extends": "../../.eslintrc.json",
  "ignorePatterns": [
    "!**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "projects/testlib/tsconfig.lib.json",
          "projects/testlib/tsconfig.spec.json"
        ],
        "createDefaultProgram": true
      },
      "rules": {
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "lib",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "lib",
            "style": "kebab-case"
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "rules": {}
    }
  ]
}
```

***

The IDEs will now display the following:

### IntelliJ

![image](https://user-images.githubusercontent.com/54843950/127289137-de7f13d4-7534-4d2c-a9a1-6a0fb78ec37b.png)

### VS Code

![image](https://user-images.githubusercontent.com/54843950/127289401-e53c8f4b-a288-4c10-ac9d-2795b6282713.png)

***

With `"tsconfigRootDir": "../../",` applied, it works in both editors:

### IntelliJ
![image](https://user-images.githubusercontent.com/54843950/127289665-59760137-4c3c-487c-b1a0-b4cf8bd3f13c.png)

### VS Code

![image](https://user-images.githubusercontent.com/54843950/127289711-2deb0455-bc47-4614-a092-730f08b08bf0.png)

**Comment by ChristophRSG** [comment]
Closing, because now it seems to work without the option.

I didn't change anything. A bit of a weird issue but since it works, it works.

Thank you for all the work you are doing! :)

**Comment by ChristophRSG** [comment]
Reopening, since it's an issue again, maybe it was caching the config before.

**Comment by guillermoarellano** [comment]
I am having this same issue. Any help will be greatly appreciated.

**Comment by guillermoarellano** [comment]
@ChristophRSG I solve this issue by following the steps described by @prabh-62 on this issue link: <https://github.com/angular-eslint/angular-eslint/issues/462#issuecomment-858073819>. 

Hopefully, this helps you and others.

**Comment by ChristophRSG** [comment]
Thank you for the suggestion @guillermoarellano !

Unfortunately, I got a root level `.eslintrc` file; it's a root level project with nested projects in it. The eslint files look exactly like the ones you linked, but with that setup I got the error above as described.

**Comment by VictorienTardif** [comment]
Hi, any news on this? I have the same problem but unfortunately adding `tsconfigRootDir` breaks `ng lint`.
It works either for the IDE either for `ng lint` but never for both.

**Comment by sagrawal31** [comment]
I also wasted my 4-5 hours trying to fix this issue with IntelliJ. Ultimately, I had to enable `Manual ESLint configuration` in IntelliJ with `Working directories` set to `./`.

![image](https://user-images.githubusercontent.com/1804514/153845168-275e74af-0a4f-4f5e-b9ca-bc1b0ed30790.png)

**Comment by guillermoarellano** [comment]
I believe this is now solved as of `13.2.0`. 

cc: @JamesHenry

**Comment by sagrawal31** [comment]
Amazing, thanks!

**Comment by sagrawal31** [comment]
I'm still seeing this issue in the latest versions.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/1804514/162495489-1065b0f0-4255-487f-901e-51301a817147.png">

**Comment by ahoenerBE** [comment]
Just got it today but solved by @sagrawal31's fix.
Saw a suggestion on YouTrack for this as well but it requires making the subprojects into `.eslintrc.js` files to use __dirname. 
This works better

**Comment by stephanie-dm** [comment]
I'm still seeing this problem with angular-eslint 15.2.1

**Comment by JamesHenry** [comment]
Hi Folks, I'm sorry that no definitive solution was applied at the time on this one, it slipped through the cracks.

Now in May 2025 things could hardly look more different. We have a totally different configuration format for ESLint, so called "flat config" via (eslint.config.js etc), and the recommended way to use type information with typescript-eslint has changed to be the `projectService: true` in `parserOptions`, which doesn't require any additional configuration for monorepos.

In light of all of this I will close this one, but please feel free to open a fresh issue if you encounter problems with the latest (ESLint v9, typescript-eslint v8, angular-eslint v19)
