### ISSUE TITLE
ng lint: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by cesco69** [angular-eslint/angular-eslint#790]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present

### Description

After install `@angular-eslint/schematics` on new project, run `ng lint` raise exception `NOT SUPPORTED: keyword "id", use "$id" for schema ID`

## 🔬 Minimal Reproduction

```
ng new my-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/ documentation/syntax#scss]
CREATE my-app/angular.json (3207 bytes)
CREATE my-app/package.json (1070 bytes)
CREATE my-app/README.md (1051 bytes)
CREATE my-app/tsconfig.json (863 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (620 bytes)
CREATE my-app/.browserslistrc (600 bytes)
CREATE my-app/karma.conf.js (1423 bytes)
CREATE my-app/tsconfig.app.json (287 bytes)
CREATE my-app/tsconfig.spec.json (333 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2338 bytes)
CREATE my-app/src/styles.scss (80 bytes)
CREATE my-app/src/test.ts (745 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (658 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.html (24617 bytes)
CREATE my-app/src/app/app.component.spec.ts (1073 bytes)
CREATE my-app/src/app/app.component.ts (211 bytes)
CREATE my-app/src/app/app.component.scss (0 bytes)
V Packages installed successfully.

cd my-app

ng add @angular-eslint/schematics
i Using package manager: npm
V Found compatible package version: @angular-eslint/schematics@1.2.0.
V Package information loaded.

The package @angular-eslint/schematics@1.2.0 will be installed and executed.
Would you like to proceed? Yes
V Package successfully installed.

An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for sche
ma ID
See "angular-errors.log" for furt her details.

```

**angular-errors.log**

```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (\my-app\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (\my-app\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at \my-app\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (\my-app\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (\my-app\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (\my-app\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (\my-app\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at \my-app\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (\my-app\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (\my-app\node_modules\ajv\dist\compile\codegen\index.js:568:18)
```

## 🔥 Exception or Error

<pre><code>
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.0.1
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Comment by JamesHenry** [comment]
Hi @cesco69, you need to use the v13 prerelease with Angular 13:

`ng add @angular-eslint/schematics@next`

Please see #715

**Comment by ullalaaron** [comment]
I have the same issue running `ng g c/s/m <name>`
This are my relevant versions
```
    "@angular-devkit/build-angular": "13.2.5",
    "@angular-eslint/builder": "13.1.0",
    "@angular-eslint/eslint-plugin": "13.1.0",
    "@angular-eslint/eslint-plugin-template": "13.1.0",
    "@angular-eslint/schematics": "13.1.0",
    "@angular-eslint/template-parser": "13.1.0",
    "@angular/cli": "13.2.5",
    "@angular/compiler-cli": "13.2.4",
```

**Comment by muzyka-viacheslav** [comment]
I do still have the same issue as well.
Not sure why it's closed.
`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID`
Angular `13.3.8` and eslint bundle `13.2.1`

**Comment by Korsarro69** [comment]
I still have the issue after running `ng add @angular-eslint/schematics@next` Same error as well. Angular core `13.3.10`, eslint `13.0.0-alpha.1` and `13.2.1`

**Comment by danleedham** [comment]
Just to confirm https://github.com/angular-eslint/angular-eslint/issues/790#issuecomment-962988420 works with anyone currently adding angular-eslint to an Angular v14 project.

**Comment by stianrincon** [comment]
this `ng add @angular-eslint/schematics@next` works, but I hade to remove the folder `node_modules`

**Comment by alexbruno** [comment]
After `v14-lts` release, if you are using any specific Angular major version, it is better to install schematics matching the Angular version.
For example, I'm using Angular `v14-lts`, so I'm installing schematics this way:

`ng add @angular-eslint/schematics@14`

**Comment by karimerrebai** [comment]
hello i got this error 
NOT SUPPORTED: keyword "id", use "$id" for schema ID when iwant to install angular material  !! how to fix this

**Comment by Jorgeflowers18** [comment]
I got the schematics @13 but it still throw the unhandled error
NOT SUPPORTED: keyword "id", use "$id" for schema ID

**Comment by pankajparkar** [comment]
I've fixed the error by following the steps

**Steps**
1. Checked the released page here - https://github.com/angular-eslint/angular-eslint/releases
2. Checked the current angular version (mine was 14.0.0)
3. Then I ran `ng add` command on a specific version
4. `ng add @angular-eslint/schematics@14.0.0` 

@karimerrebai and @Jorgeflowers18 may be you can also give a shot by above steps.

**Comment by cseas** [comment]
I ran the steps to migrate Angular & material from 12 to 13.
Then ran `ng add @angular-eslint/schematics@13.5.0`
Still getting this error.

**Comment by fmotorny** [comment]
After migrate angular 9 > 14  when i genereate some component with CLI then I was getting this error:

- An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

In my case i found old dependence (@schematics/angular": "9.1.0") and remove, then it works

**Comment by ashwiniLiman** [comment]
Getting "An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID" after migrating Angular 14 to 15.

**Comment by JamesHenry** [comment]
Folks there is no issue with angular-eslint here and that’s been the case for a very long time now.

100% of the time this is down to rogue old Angular dependencies on your machine. It’s not something that can be resolved by tooling you will need to troubleshoot your setup.

You can try lots of things to fix your machine:

First run ng version to see what version of the packages it resolves. If any of them do not match the first number you have already found the problem.

If still an issue you need to try and remove any outdated cached packages that might somehow exist. Some ideas:

- Remove your node_modules and delete your lock file and rebuild it with a fresh install
- Force clean your global npm cache
- delete your npx cache

Hope that helps, but please stop adding to this resolved issue, there is nothing to “fix” in angular-eslint

**Comment by TiagoBarbosa88** [comment]
I also had the same problem, I managed to solve it by installing an earlier version of angular material

ng add @angular/material@14.2.7

**Comment by clmauriciosoto** [comment]
Would you like to add a package with "deploy" capabilities now? GitHub Pages
Skipping installation: Package already installed
NOT SUPPORTED: keyword "id", use "$id" for schema ID

angular 16

**Comment by ovanderzee** [comment]
When you are offered  to run @angular-eslint/schematics@1.x.x, use run @angular-eslint/schematics@[your angular version]

**Comment by dkondrashin** [comment]
In my case the reason was old version of @angular-builders/custom-webpack.
After upgrading @angular-builders/custom-webpack according to other Angular libraries, the problem has vanished.
